# Generated by Django 5.2 on 2025-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('selling', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='selling', max_length=10),
        ),
    ]
